---
title: Eek.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
url: https://eek.ro
isDevelopment: false
harmony:
  name: Tech and all things bleeding edge
  meta_description: 'Eek''s Blog is a blog about programming, tech and entrepreneurship.

'
  basetheme: theme-base-01
  author:
    name: Radu-Sebastian Amarie
    email: raduamarie@gmail.com
    url: http://eek.ro
  google_analytics_key: UA-16595407-1
  social:
    linkedin: raduamarie
    github: eek
    twitter: raduamarie
    facebook: raduamarie
    gplus: '106516470902631975813'
  show_disclaimer: false
markdown: kramdown
highlighter: rouge
permalink: "/:slug/"
exclude:
- CNAME
- Gemfile
- Rakefile
- README.md
- ".gitignore"
- ".sass-cache"
- Gemfile.lock
sass:
  sass_dir: assets/css/_sass
  style: :compressed
